// <auto-generated />
namespace Microsoft.AspNet.OAuth.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createOAuthMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createOAuthMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201804191842125_createOAuthMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
