// <auto-generated />
namespace Micosoft.AspNet.Identiey.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createAspNetIdentiey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createAspNetIdentiey));
        
        string IMigrationMetadata.Id
        {
            get { return "201804121733391_createAspNetIdentiey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
